# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code quality checks

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality-pnpm-workflow.yaml
    with:
      check-command: 'pnpm exec nmr ci'
