# https://github.com/marketplace/actions/github-labeler
name: Set issue labels

on:
  workflow_dispatch: {}

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout consumer repo
        uses: actions/checkout@v4

      - name: Ensure labels.yaml exists
        run: |
          if [ ! -f ".github/labels.yaml" ]; then
            echo "No .github/config/issue-labels.yaml found — using default"
            curl -sSL -o .github/config/issue-labels.yaml https://raw.githubusercontent.com/williamthorsen/.github/main/.github/config/issue-labels.yaml
          fi

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/config/issue-labels.yaml
          skip-delete: false
          dry-run: false
